---
- hosts: all
  become: yes
  tasks:
    - name: Установка nginx
      apt:
        name: nginx
        state: present
      when: ansible_facts['os_family'] == "Debian"

    - name: Запуск и включение nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Проверка работы nginx
      uri:
        url: http://{{ ansible_host }}
        status_code: 200
      register: result
      failed_when: "'200' not in result.status|string"
